// Package app bootstraps and runs the application.
package app

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"wishlist-api/internal/config"
	"wishlist-api/internal/db"
	"wishlist-api/internal/handlers"
	"wishlist-api/internal/middleware"
	"wishlist-api/internal/repository"
	"wishlist-api/internal/service"

	"github.com/go-chi/chi/v5"
	chiMiddleware "github.com/go-chi/chi/v5/middleware"
	"github.com/jackc/pgx/v5/pgxpool"
	httpSwagger "github.com/swaggo/http-swagger"

	// Swagger documentation generated by swaggo/swag
	_ "wishlist-api/docs"
)

const shutdownTimeout = 5 * time.Second

// App holds all application dependencies and the HTTP server.
type App struct {
	cfg    *config.Config
	dbPool *pgxpool.Pool
	router *chi.Mux
	server *http.Server
}

// New creates and configures a new App instance.
func New(ctx context.Context, cfg *config.Config) (*App, error) {
	pool, err := createDBPool(ctx, cfg)
	if err != nil {
		return nil, fmt.Errorf("create db pool: %w", err)
	}

	repos := initRepositories(pool)
	services := initServices(repos, cfg)
	router := initRouter(services, cfg)

	server := &http.Server{
		Addr:    ":" + cfg.AppPort,
		Handler: router,
	}

	return &App{
		cfg:    cfg,
		dbPool: pool,
		router: router,
		server: server,
	}, nil
}

// createDBPool establishes connection to PostgreSQL.
func createDBPool(ctx context.Context, cfg *config.Config) (*pgxpool.Pool, error) {
	pool, err := db.NewPostgresPool(ctx, cfg.DBHost, cfg.DBPort, cfg.DBUser, cfg.DBPassword, cfg.DBName)
	if err != nil {
		return nil, fmt.Errorf("connect to database: %w", err)
	}
	return pool, nil
}

type repositories struct {
	user     *repository.UserPostgres
	wishlist *repository.WishlistPostgres
	item     *repository.ItemPostgres
}

func initRepositories(pool *pgxpool.Pool) *repositories {
	return &repositories{
		user:     repository.NewUserRepository(pool),
		wishlist: repository.NewWishlistRepository(pool),
		item:     repository.NewItemRepository(pool),
	}
}

type services struct {
	auth     *service.AuthService
	wishlist *service.WishlistService
	item     *service.ItemService
}

func initServices(repos *repositories, cfg *config.Config) *services {
	authSvc := service.NewAuthService(repos.user, cfg.JWTSecret, cfg.JWTExpiryHours)
	wishlistSvc := service.NewWishlistService(repos.wishlist)
	itemSvc := service.NewItemService(repos.item, repos.wishlist)

	return &services{
		auth:     authSvc,
		wishlist: wishlistSvc,
		item:     itemSvc,
	}
}

func initRouter(svc *services, cfg *config.Config) *chi.Mux {
	authHandler := handlers.NewAuthHandler(svc.auth)
	wishlistHandler := handlers.NewWishlistHandler(svc.wishlist, svc.item)
	itemHandler := handlers.NewItemHandler(svc.item)
	publicHandler := handlers.NewPublicHandler(svc.wishlist, svc.item)

	corsCfg := middleware.CorsConfig{
		AllowedOrigins: cfg.CORSOrigins,
		AllowedMethods: []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
		AllowedHeaders: []string{"Content-Type", "Authorization", "X-Request-ID"},
	}

	// CSRF protection (Go 1.25+)
	csrfMiddleware := http.NewCrossOriginProtection()
	for _, origin := range cfg.CORSOrigins {
		if origin != "*" {
			if err := csrfMiddleware.AddTrustedOrigin(origin); err != nil {
				slog.Warn("failed to add trusted origin for CSRF", "origin", origin, "error", err)
			}
		}
	}

	r := chi.NewRouter()
	r.Use(middleware.CorsMiddleware(corsCfg))
	r.Use(middleware.RequestIDMiddleware)
	r.Use(csrfMiddleware.Handler)
	r.Use(chiMiddleware.Logger)
	r.Use(chiMiddleware.Recoverer)

	// Public routes
	r.Post("/auth/register", authHandler.Register)
	r.Post("/auth/login", authHandler.Login)
	r.Get("/public/wishlists/{token}", publicHandler.GetWishlistByToken)
	r.Post("/public/wishlists/{token}/items/{item_id}/book", publicHandler.BookItem)

	// Protected routes
	r.Group(func(r chi.Router) {
		r.Use(middleware.AuthMiddleware(svc.auth))
		r.Route("/wishlists", func(r chi.Router) {
			r.Post("/", wishlistHandler.Create)
			r.Get("/", wishlistHandler.GetAll)
			r.Get("/{id}", wishlistHandler.GetByID)
			r.Put("/{id}", wishlistHandler.Update)
			r.Delete("/{id}", wishlistHandler.Delete)
			r.Post("/{wishlist_id}/items", itemHandler.Create)
			r.Get("/{wishlist_id}/items", itemHandler.GetAll)
		})
		r.Get("/items/{id}", itemHandler.GetByID)
		r.Put("/items/{id}", itemHandler.Update)
		r.Delete("/items/{id}", itemHandler.Delete)
	})

	// Swagger
	r.Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL("/swagger/doc.json"),
	))

	return r
}

// Run starts the HTTP server and handles graceful shutdown.
func (a *App) Run() {
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)

	go func() {
		slog.Info("server started", "port", a.cfg.AppPort)
		if err := a.server.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			slog.Error("server error", "error", err)
			quit <- syscall.SIGTERM
		}
	}()

	<-quit
	slog.Info("shutting down...")

	ctx, cancel := context.WithTimeout(context.Background(), shutdownTimeout)
	defer cancel()

	if err := a.server.Shutdown(ctx); err != nil {
		slog.Error("shutdown error", "error", err)
	}

	a.dbPool.Close()
	slog.Info("server stopped")
}
