basePath: /
definitions:
  dto.CreateItemRequest:
    properties:
      description:
        maxLength: 1000
        type: string
      priority:
        maximum: 5
        minimum: 1
        type: integer
      product_link:
        type: string
      title:
        maxLength: 255
        minLength: 1
        type: string
    required:
    - priority
    - title
    type: object
  dto.CreateWishlistRequest:
    properties:
      description:
        maxLength: 1000
        type: string
      event_date:
        type: string
      title:
        maxLength: 255
        minLength: 1
        type: string
    required:
    - event_date
    - title
    type: object
  dto.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dto.LoginResponse:
    properties:
      token:
        type: string
    type: object
  dto.RegisterRequest:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  dto.UpdateItemRequest:
    properties:
      description:
        maxLength: 1000
        type: string
      priority:
        maximum: 5
        minimum: 1
        type: integer
      product_link:
        type: string
      title:
        maxLength: 255
        minLength: 1
        type: string
    type: object
  dto.UpdateWishlistRequest:
    properties:
      description:
        maxLength: 1000
        type: string
      event_date:
        type: string
      title:
        maxLength: 255
        minLength: 1
        type: string
    type: object
  models.Item:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      is_booked:
        type: boolean
      priority:
        type: integer
      product_link:
        type: string
      title:
        type: string
      updated_at:
        type: string
      wishlist_id:
        type: integer
    type: object
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      updated_at:
        type: string
    type: object
  models.Wishlist:
    properties:
      access_token:
        type: string
      created_at:
        type: string
      description:
        type: string
      event_date:
        type: string
      id:
        type: integer
      items:
        items:
          $ref: '#/definitions/models.Item'
        type: array
      title:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: REST API сервис для создания вишлистов и бронирования подарков.
  title: Wishlist API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LoginResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: Login user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: User data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            type: string
        "409":
          description: Conflict
          schema:
            type: string
      summary: Register new user
      tags:
      - auth
  /items/{id}:
    delete:
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Delete item
      tags:
      - items
    put:
      consumes:
      - application/json
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated fields
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateItemRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Update item
      tags:
      - items
  /public/wishlists/{token}:
    get:
      parameters:
      - description: Access token (UUID)
        in: path
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Wishlist'
      summary: Get public wishlist by access token
      tags:
      - public
  /public/wishlists/{token}/items/{item_id}/book:
    post:
      parameters:
      - description: Access token (UUID)
        in: path
        name: token
        required: true
        type: string
      - description: Item ID
        in: path
        name: item_id
        required: true
        type: integer
      responses:
        "200":
          description: booked
          schema:
            type: string
        "409":
          description: item already booked
          schema:
            type: string
      summary: Book an item in public wishlist
      tags:
      - public
  /wishlists:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Wishlist'
            type: array
        "401":
          description: Unauthorized
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Get all user's wishlists
      tags:
      - wishlists
    post:
      consumes:
      - application/json
      parameters:
      - description: Wishlist data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateWishlistRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Wishlist'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Create new wishlist
      tags:
      - wishlists
  /wishlists/{id}:
    delete:
      parameters:
      - description: Wishlist ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Delete wishlist
      tags:
      - wishlists
    get:
      parameters:
      - description: Wishlist ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Wishlist'
        "404":
          description: Not Found
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Get wishlist by ID
      tags:
      - wishlists
    put:
      consumes:
      - application/json
      parameters:
      - description: Wishlist ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated fields
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateWishlistRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Update wishlist
      tags:
      - wishlists
  /wishlists/{wishlist_id}/items:
    get:
      parameters:
      - description: Wishlist ID
        in: path
        name: wishlist_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Item'
            type: array
      security:
      - BearerAuth: []
      summary: Get all items of a wishlist
      tags:
      - items
    post:
      consumes:
      - application/json
      parameters:
      - description: Wishlist ID
        in: path
        name: wishlist_id
        required: true
        type: integer
      - description: Item data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateItemRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Item'
      security:
      - BearerAuth: []
      summary: Create item in wishlist
      tags:
      - items
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
